In [2]:
import cv2
import os
import numpy as np
from PIL import Image

Reference:
[YouTube](https://www.youtube.com/watch?v=eDIj5LuIL4A)

## image

### read a image

In [7]:
image_path = "img_test.jpg" # os.path.join('','','')
img = cv2.imread(image_path)

### write a image

In [10]:
output_path = 'img_out.jpg'
cv2.imwrite(output_path, img)

True

### visualize a image

In [13]:
cv2.imshow('image', img)
cv2.waitKey(0) ## 0 is equal to infinite
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

## video

### read a video

In [17]:
video_path = "video_scene_test.mov"
video = cv2.VideoCapture(video_path)

### visualize the video

In [22]:

while True:
    ret, frame = video.read()
    if not ret:
        break
    cv2.imshow('frame', frame)
    cv2.waitKey(40) # based on 25 frames in 1s, 1 frame 1/25*1000 1ms

## release the memory    
video.release()
cv2.destroyAllWindows()
cv2.waitKey(1)# close all the windows for mac 

-1

## webcam

In [25]:
webcam = cv2.VideoCapture(0)
while True:
    ret, frame = webcam.read()
    cv2.imshow('frame', frame)
    if cv2.waitKey(40) & 0xFF == ord('q'):
        break
        
webcam.release()
cv2.destroyAllWindows()
cv2.waitKey(1)# close all the windows for mac 

-1

## image processing

### resizing

In [29]:
img_path = 'img_test.jpg'
img = cv2.imread(img_path)
resized_img = cv2.resize(img, (640, 480))

print(img.shape)
print(resized_img)
cv2.imshow('img', img)
cv2.imshow('resized_img', resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

(736, 500, 3)
[[[250  68  36]
  [250  69  37]
  [251  71  39]
  ...
  [253  44  19]
  [254  44  20]
  [254  44  20]]

 [[233  68  35]
  [229  61  28]
  [227  56  23]
  ...
  [247  44  18]
  [247  44  18]
  [247  44  18]]

 [[217  99  59]
  [215  92  52]
  [215  83  44]
  ...
  [246  53  25]
  [246  53  25]
  [246  53  25]]

 ...

 [[ 57  54  54]
  [ 57  54  54]
  [ 56  54  53]
  ...
  [ 49  47  46]
  [ 48  46  45]
  [ 47  45  44]]

 [[ 53  52  51]
  [ 54  52  51]
  [ 55  53  52]
  ...
  [ 43  41  40]
  [ 42  40  39]
  [ 42  39  38]]

 [[ 51  49  48]
  [ 52  50  49]
  [ 54  52  51]
  ...
  [ 41  39  38]
  [ 40  38  37]
  [ 40  38  37]]]


-1

### cropping

In [31]:
img_path = 'img_test.jpg'
img = cv2.imread(img_path)

# NPR right
cropped_img = img[150:600, 0:600]

print(img.shape)

cv2.imshow('img', img)
cv2.imshow('cropped_img', cropped_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

(736, 500, 3)


-1

### color space convert

In [34]:
img_path = 'img_test.jpg'
img = cv2.imread(img_path)
# cv2 BGR

img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # thresholding for edge detection, intensity
# BGR -> RGB
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# RGB -> BGR
img_bgr = img_rgb[:, :, ::-1]
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV) # for color-based segmentation, adjustment

cv2.imshow('img', img)
cv2.imshow('img_gray', img_gray)
cv2.imshow('img_rgb', img_rgb)
cv2.imshow('img_bgr', img_bgr)
cv2.imshow('img_hsv', img_hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

### bluring

In [36]:
img_path = 'img_test.jpg'
img = cv2.imread(img_path)
k_size = 85
img_blur = cv2.blur(img, (k_size, k_size)) ## the average of the sized neighbour 
img_gaussian_blur = cv2.GaussianBlur(img, (k_size, k_size), 1) ## kernel must be odd
img_median_blur = cv2.medianBlur(img, k_size)
cv2.imshow('img', img)
cv2.imshow('img_blur', img_blur)
cv2.imshow('img_gaussian_blur', img_gaussian_blur)
cv2.imshow('img_median_blur', img_median_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

### threshold

In [38]:
img_path = 'img_test.jpg'
img = cv2.imread(img_path)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


adaptive_thresh = cv2.adaptiveThreshold(img_gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 21, 30)
ret, simple_thresh = cv2.threshold(img_gray, 80, 255, cv2.THRESH_BINARY)

cv2.imshow('img', img)
cv2.imshow('img_gray', img_gray)
cv2.imshow('simple_thresh', simple_thresh)
cv2.imshow('adaptive_thresh', adaptive_thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

### edge detection

In [40]:
img_path = 'img_test.jpg'
img = cv2.imread(img_path)
img_edge = cv2.Canny(img, 100, 200)
img_edge_d = cv2.dilate(img_edge, np.ones((3, 3), dtype = np.int8))
img_edge_e = cv2.erode(img_edge_d, np.ones((3, 3), dtype = np.int8))
cv2.imshow('img', img)
cv2.imshow('img_edge', img_edge)
cv2.imshow('img_edge_d', img_edge_d)
cv2.imshow('img_edge_e', img_edge_e)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

### drawing

In [42]:
img_path = 'img_test.jpg'
img = cv2.imread(img_path)
print(img.shape)

(736, 500, 3)


#### line

In [45]:
# starting point to end point
cv2.line(img, (100, 150), (150, 300), (0, 255, 0), 3)

array([[[249,  66,  34],
        [254,  71,  39],
        [255,  77,  46],
        ...,
        [254,  44,  20],
        [255,  44,  20],
        [255,  45,  21]],

       [[252,  75,  42],
        [242,  65,  32],
        [242,  61,  29],
        ...,
        [250,  43,  18],
        [250,  43,  18],
        [250,  43,  18]],

       [[229,  66,  33],
        [223,  56,  23],
        [225,  52,  19],
        ...,
        [246,  45,  18],
        [246,  45,  18],
        [246,  45,  18]],

       ...,

       [[ 54,  52,  51],
        [ 55,  53,  52],
        [ 55,  53,  52],
        ...,
        [ 44,  42,  41],
        [ 43,  41,  40],
        [ 42,  40,  39]],

       [[ 52,  50,  49],
        [ 54,  52,  51],
        [ 55,  53,  52],
        ...,
        [ 42,  40,  39],
        [ 40,  38,  37],
        [ 40,  38,  37]],

       [[ 51,  49,  48],
        [ 53,  51,  50],
        [ 55,  53,  52],
        ...,
        [ 42,  40,  39],
        [ 41,  39,  38],
        [ 40,  38,  37]]

#### rectangle

In [48]:
# top-left to bottom-right
cv2.rectangle(img, (150, 300), (350, 500), (0, 0, 255), 5)
cv2.rectangle(img, (300, 400), (350, 450), (0, 0, 255), -1)

array([[[249,  66,  34],
        [254,  71,  39],
        [255,  77,  46],
        ...,
        [254,  44,  20],
        [255,  44,  20],
        [255,  45,  21]],

       [[252,  75,  42],
        [242,  65,  32],
        [242,  61,  29],
        ...,
        [250,  43,  18],
        [250,  43,  18],
        [250,  43,  18]],

       [[229,  66,  33],
        [223,  56,  23],
        [225,  52,  19],
        ...,
        [246,  45,  18],
        [246,  45,  18],
        [246,  45,  18]],

       ...,

       [[ 54,  52,  51],
        [ 55,  53,  52],
        [ 55,  53,  52],
        ...,
        [ 44,  42,  41],
        [ 43,  41,  40],
        [ 42,  40,  39]],

       [[ 52,  50,  49],
        [ 54,  52,  51],
        [ 55,  53,  52],
        ...,
        [ 42,  40,  39],
        [ 40,  38,  37],
        [ 40,  38,  37]],

       [[ 51,  49,  48],
        [ 53,  51,  50],
        [ 55,  53,  52],
        ...,
        [ 42,  40,  39],
        [ 41,  39,  38],
        [ 40,  38,  37]]

#### circle

In [51]:
cv2.circle(img, (300,400), 50, (250, 0, 0), 5)

array([[[249,  66,  34],
        [254,  71,  39],
        [255,  77,  46],
        ...,
        [254,  44,  20],
        [255,  44,  20],
        [255,  45,  21]],

       [[252,  75,  42],
        [242,  65,  32],
        [242,  61,  29],
        ...,
        [250,  43,  18],
        [250,  43,  18],
        [250,  43,  18]],

       [[229,  66,  33],
        [223,  56,  23],
        [225,  52,  19],
        ...,
        [246,  45,  18],
        [246,  45,  18],
        [246,  45,  18]],

       ...,

       [[ 54,  52,  51],
        [ 55,  53,  52],
        [ 55,  53,  52],
        ...,
        [ 44,  42,  41],
        [ 43,  41,  40],
        [ 42,  40,  39]],

       [[ 52,  50,  49],
        [ 54,  52,  51],
        [ 55,  53,  52],
        ...,
        [ 42,  40,  39],
        [ 40,  38,  37],
        [ 40,  38,  37]],

       [[ 51,  49,  48],
        [ 53,  51,  50],
        [ 55,  53,  52],
        ...,
        [ 42,  40,  39],
        [ 41,  39,  38],
        [ 40,  38,  37]]

#### text

In [54]:
cv2.putText(img, 'it is cold, isnt it?', (100, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 0), 2)

array([[[249,  66,  34],
        [254,  71,  39],
        [255,  77,  46],
        ...,
        [254,  44,  20],
        [255,  44,  20],
        [255,  45,  21]],

       [[252,  75,  42],
        [242,  65,  32],
        [242,  61,  29],
        ...,
        [250,  43,  18],
        [250,  43,  18],
        [250,  43,  18]],

       [[229,  66,  33],
        [223,  56,  23],
        [225,  52,  19],
        ...,
        [246,  45,  18],
        [246,  45,  18],
        [246,  45,  18]],

       ...,

       [[ 54,  52,  51],
        [ 55,  53,  52],
        [ 55,  53,  52],
        ...,
        [ 44,  42,  41],
        [ 43,  41,  40],
        [ 42,  40,  39]],

       [[ 52,  50,  49],
        [ 54,  52,  51],
        [ 55,  53,  52],
        ...,
        [ 42,  40,  39],
        [ 40,  38,  37],
        [ 40,  38,  37]],

       [[ 51,  49,  48],
        [ 53,  51,  50],
        [ 55,  53,  52],
        ...,
        [ 42,  40,  39],
        [ 41,  39,  38],
        [ 40,  38,  37]]

In [56]:
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

### contours

In [59]:
img_path = 'img_test.jpg'
img = cv2.imread(img_path)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(img_gray, 127, 255, cv2.THRESH_BINARY_INV)
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

for cnt in contours:
    print(cv2.contourArea(cnt))
    # fiter, large area
    if cv2.contourArea(cnt) > 5000:
        # draw contour
        cv2.drawContours(img, cnt, -1, (0, 255, 0), 1)
        
        x1, y1, w, h = cv2.boundingRect(cnt)
        # draw box
        cv2.rectangle(img,(x1, y1), (x1 + w, y1 + h), (0, 255, 0), 2)
        
cv2.imshow('img', img)
cv2.imshow('img_gray', img_gray)
cv2.imshow('thresh', thresh)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

0.5
4.0
1.5
0.0
3.5
6.5
0.0
0.0
0.0
0.0
1.5
0.0
0.0
3.5
0.0
43.5
2.0
2.0
2.0
2.0
4.0
0.0
0.0
0.0
1.5
0.0
0.0
0.0
0.0
0.0
13.0
0.0
0.5
2.5
0.0
0.0
0.0
0.0
0.0
2.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
314.5
6.0
2.0
0.0
0.0
117.5
0.0
0.0
0.0
0.0
0.0
0.0
13.0
0.0
0.0
6.5
0.0
0.0
0.0
0.0
1.0
318.0
2.0
0.0
0.0
0.0
5.5
2.0
0.0
1.0
0.0
0.0
0.0
0.5
4.0
0.0
0.0
0.0
0.0
6.5
0.0
87.0
0.0
15.0
1.5
0.0
0.0
17.5
0.0
0.5
0.0
0.0
0.0
0.0
6.0
0.0
0.0
47.0
0.0
22.0
110.5
2.0
0.0
136.5
2.0
2.0
542.5
2.0
2.0
52.0
0.0
0.0
31.0
33.5
0.0
0.0
0.0
3.0
0.0
0.5
0.0
0.0
82.0
0.0
0.0
0.0
0.0
0.0
0.0
0.5
0.0
0.5
0.5
13.5
0.0
0.0
0.0
0.5
0.0
123.5
30.5
2.0
59.5
5.5
0.0
0.0
0.5
0.0
0.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
31.5
2.0
0.0
0.0
2.5
0.0
0.0
0.0
5.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
9.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.5
0.0
0.0
1.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
24.5
5.0
0.0
0.0
0.0
28.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.0
0.0
0.0
0.0
22.0
2.0
4.0
0.0
10.0
2.0
42.5
0.0
7.0
6.5
0.5
0.0
0.0
13.0
0.0
0.0
17.0
0.0
0.0
6.0
0.0

-1

## color detector

In [61]:
def get_limits(color):
    c_input = np.uint8([[color]])
    hsv_c = cv2.cvtColor(c_input, cv2.COLOR_BGR2HSV)
    
    lower_limit = hsv_c[0][0][0] - 10, 100, 100
    upper_limit = hsv_c[0][0][0] + 10, 255, 255
    
    lower_limit = np.array(lower_limit, dtype=np.uint8)
    upper_limit = np.array(upper_limit, dtype=np.uint8)
    
    return lower_limit, upper_limit

In [67]:
yellow = [0, 255, 255] # yellow in RGB color space
cap = cv2.VideoCapture(0)
while True:
    ret, frame = cap.read()

    hsv_img = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    lower_limit, upper_limit = get_limits(color = yellow)
    
    mask = cv2.inRange(hsv_img, lower_limit, upper_limit)
    mask_ = Image.fromarray(mask)
    
    # get a boinding box
    bbox = mask_.getbbox()
    print(bbox)
    if bbox is not None:
        x1, y1, x2, y2 = bbox
        frame = cv2.rectangle(frame, (x1, y1, x2, y2), (0, 255, 0), 5)
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)# close all the windows for mac 

None
None
(394, 405, 396, 411)
None
None
(1215, 275, 1228, 282)
(393, 473, 1279, 534)
(41, 330, 546, 655)
None
None
None
None
(1275, 124, 1279, 126)
None
None
None
None
(1272, 676, 1280, 682)
None
None
None
None
None
(1276, 232, 1280, 234)
None
None
None
(133, 657, 137, 658)
None
None
None
None
(1270, 247, 1273, 251)
(1256, 246, 1265, 252)
None
None
None
None
None
None
None
(1279, 486, 1280, 487)
None
None
None
None
None
None
None
None
None
(430, 463, 433, 466)
None
None
None
None
None
None
None
None
None
None
None
(1235, 323, 1236, 324)
None
(1258, 204, 1259, 205)
None
None
(36, 649, 37, 650)
None
None
None
None
(1238, 273, 1239, 274)
(1205, 174, 1280, 230)
None
(44, 648, 47, 650)
None
None
None
(0, 238, 192, 671)
None
(1231, 316, 1245, 323)
None
None
None
None
None
None
None
None
None
(2, 652, 3, 654)
None
(1278, 218, 1280, 219)
(1277, 218, 1280, 221)
(1254, 142, 1259, 144)
None
(1276, 232, 1277, 233)
None
None
None
None
None
None
None
(12, 510, 21, 512)
None
(1218, 335, 1219, 337)
(

-1

## face anonymizer

In [ ]:
conda create -n face_detection python=3.11 -y

In [ ]:
pip install mediapipe

In [69]:
import mediapipe as mp
import argparse


def process_face_img(img_input, face_detection):
    img_rgb = cv2.cvtColor(img_input, cv2.COLOR_BGR2RGB)
    H, W, _ = img_input.shape
    out = face_detection.process(img_rgb)
    if out.detections is not None:
        for detection in out.detections:
            location_data = detection.location_data
            bbox = location_data.relative_bounding_box
            x1, y1, w, h = bbox.xmin, bbox.ymin, bbox.width, bbox.height
            x1 = int(x1 * W)
            y1 = int(y1 * H)
            w = int(w * W)
            h = int(h * H)
            #blur
            img_input[y1:y1+h, x1:x1+w, :] = cv2.blur(img_input[y1:y1+h, x1:x1+w, :], (10, 10))
            # bounding box
            img = cv2.rectangle(img_input, (x1, y1), (x1+w, y1+h), (0, 255, 0), 10)

    return img_input

#
args = argparse.ArgumentParser()

'''
#img
args.add_argument('--mode', default='image')
args.add_argument('--filePath', default='img_test.jpg')
'''


#video
args.add_argument('--mode', default='video')
args.add_argument('--filePath', default='video_face_test.mov')


'''
#webcam
args.add_argument('--mode', default='webcam')
'''

#args = args.parse_args() # jupyternotebook will report error for -f 
args, unknown = args.parse_known_args()
output_dir = './output'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)


mp_face_detection = mp.solutions.face_detection
with mp_face_detection.FaceDetection(model_selection=0, min_detection_confidence=0.5) as face_detection:
    if args.mode in ['image']:
        img = cv2.imread(args.filePath)

        img = process_face_img(img, face_detection)
    
        # cv2.imshow('img', img)
        # cv2.waitkey(0)
        cv2.imwrite(os.path.join(output_dir, 'output_face.png'), img)
    elif args.mode in ['video']:
        
        cap = cv2.VideoCapture(args.filePath)
        ret, frame = cap.read()

        out_video = cv2.VideoWriter(os.path.join(output_dir, 'video_face_test.mov'),
                                   cv2.VideoWriter_fourcc(*'avc1'),
                                   25,
                                   (frame.shape[1], frame.shape[0]))
        while ret:
            frame = process_face_img(frame, face_detection)
            out_video.write(frame)
            ret, frame = cap.read()
        cap.release()
        out_video.release()
    elif args.mode in['webcam']:
        print("webcam")
        cap = cv2.VideoCapture(0)
        ret, frame = cap.read()
        while ret:
            frame = process_face_img(frame, face_detection)
            cv2.imshow('frame', frame)
            if cv2.waitKey(0) & 0xFF == ord('q'):
                break
            ret, frame = cap.read()
        cap.release()
        cv2.destroyAllWindows()
        cv2.waitKey(1)# close all the windows for mac 

I0000 00:00:1763864996.558076 1032687 gl_context.cc:369] GL version: 2.1 (2.1 INTEL-22.5.10), renderer: Intel(R) Iris(TM) Plus Graphics 645
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1763864996.596042 1039052 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
